<?php
require_once __DIR__ . '/config/database.php';

$review_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if ($review_id > 0) {
    $stmt = $pdo->prepare("SELECT r.*, u.username FROM reviews r JOIN users u ON r.user_id = u.id WHERE r.id = ?");
    $stmt->execute([$review_id]);
    $review = $stmt->fetch();

    if ($review) {
        $filename = "Review_" . preg_replace('/[^a-zA-Z0-9]/', '_', $review['movie_title']) . ".txt";
        
        header('Content-Type: text/plain; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');

        echo "========================================\n";
        echo "🎬 Movie: " . $review['movie_title'] . "\n";
        echo "👤 Author: " . $review['username'] . "\n";
        echo "📅 Date: " . $review['created_at'] . "\n";
        echo "⭐ Rating: " . $review['star_rating'] . "/5\n";
        echo "========================================\n\n";
        echo "[AI Summary]\n";
        echo ($review['summary'] ?: "No summary available.") . "\n\n";
        echo "[Review Content]\n";
        echo $review['content'] . "\n\n";
        echo "========================================\n";
        echo "Generated by CineAI\n";
        exit;
    }
}

die("Review not found.");
?>
